services:
  uptime-kuma:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    image: omid-bank-monitoring:local
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3002:3001"
